### ISSUE TITLE
[issue] with addon Umbrella

### ISSUE THREAD

**Issue by Nuklear92** [ivarbrandt/skin.nimbus#134]
So, I'm not sure if this is an issue that needs to be fixed by the addon's dev or it could be fixed by you. 

So, the issue seems to be that Nimbus isn't marking caught up/watched or finished items with the checkmarks like FenLight does. As you'll see in both screenshots below the one that has the checkmarks with the titles is from Fen addon and the one who doesn't have is Umbrella addon. Same it's happening to the seasons as well, only episodes seems to have the checkmark indicating that the item has been watched. 

**Umbrella addon as you see no checkmarks within the title/season posters indicating the item is caught up or finished.**

![image](https://github.com/user-attachments/assets/d8fe1846-ad83-40ad-8695-fa334116c226)

**FenLight Addon shows the checkmarks within title/season posters**

![image](https://github.com/user-attachments/assets/16295580-28b5-4ad5-8f88-112a320c77de)

**Comment by ivarbrandt** [comment]
I have no idea.

**Comment by Nuklear92** [comment]
> I have no idea.

I see, thanks. I'll see if I can somehow get in touch with the dev of the add-on and see if that's fixable from his end.

**Comment by ivarbrandt** [comment]
Yeah I would need to know what property he uses to show progress. I thought it was the same as Fen/Light but that might just be POV and all the other Fen forks.

**Comment by ivarbrandt** [comment]
This is the value that displays check marks when something has been watched:

`<value condition="Integer.IsGreater(ListItem.Playcount,0)">OverlayWatched.png</value>`

**Comment by ivarbrandt** [comment]
This has been fixed for next update. 
@umbrellaplug, no changes are necessary on your part.

**Comment by ivarbrandt** [comment]
Update is up.

**Comment by Nuklear92** [comment]
Doubled checked after installing the update and indeed now watched/caught up TV Shows are showing checkmarks ✔️ 

Thanks for the fix! 💙

**Comment by Nuklear92** [comment]
@ivarbrandt Hey, I just discovered after making some Home Screen widgets that this issue wasn't fixed there. It's fixed if you're navigating within the addon itself only. Hopefully whatever fix you applied for the addon can be applied to widgets as well.
